### ISSUE TITLE
rm doesn't work?

### ISSUE THREAD

**Issue by ashb** [SocialFlowDev/SocialFlow-S3#2]
The subject pretty much says it all. Example shows what I'm trying:

```
root@nfs:~# sfs3 rm -f /usr/local/etc/nfs_sfs3_cred.yml foo
Removed foo/
root@nfs:~# sfs3 ls -f /usr/local/etc/nfs_sfs3_cred.yml
2013-09-18.tgz
2013-09-19.tgz
2013-09-20.tgz
foo
```

I checked with ll-ls and the meta/foo/md5sum and data/foo still exist, and cat gives me the content.

**Comment by leonerd** [comment]
Hmm, yes. Seems some collateral from the way that it tries to expand glob patterns.

**Comment by leonerd** [comment]
Should now be fixed.

Annoyingly, S3 gives the same result after successful delete vs delete operation that didn't remove anything, so unfortunately the message can't really be improved here.
