### ISSUE TITLE
prefix specified as part of bucket configuration does not apply to push command

### ISSUE THREAD

**Issue by ghost** [SocialFlowDev/SocialFlow-S3#5]
Either my eyes lied to me, the output didn't include the prefix that was used, or the configured bucket prefix isn't applied to the push command. Its hard to tell because of a concurrent error that is preventing uploading.

**Comment by leonerd** [comment]
The bucket prefix is the part before the "data/" in the S3 keys. For example:

$ cat etc/sfs3.conf
bucket: 'a-bucket-and-some-jifjeakfjaljfeioahj/pevans-test/'

Leads to:

Na:Webservice::S3<-SocialFlow::S3] REQUEST PUT http://a-bucket-and-some-jifjeakfjaljfeioahj.s3.amazonaws.com/pevans-test/data/tree/one/A22

So the "pevans-test/" part is still present here.

The path that's was printed on the error result you pasted earlier was the local filesystem path, which wouldn't include the S3 bucket prefix.
