### ISSUE TITLE
Remove cat and uncat commands

### ISSUE THREAD

**Issue by ghost** [SocialFlowDev/SocialFlow-S3#6]
Instead of cat and uncat the standard get and put commands should accept '-' as a filename. If '-' is used as the filename then either stdin or stdout should be used. This would be following the behavior of tar.

**Comment by leonerd** [comment]
Done

https://github.com/SocialFlowDev/SocialFlow-S3/commit/146f3ebe1f64650c15a10e3e5a08b5d4a112cc50
